import type { Metadata } from "next";
import localFont from "next/font/local";
import { LiffProvider } from "@/components/LiffProvider";
import "../globals.css";
import { getMessages, getTranslations } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { CalendarDays } from "lucide-react";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const awaitedParams = await params;
  const messages = await getMessages(awaitedParams);
  const t = await getTranslations('Homepage');
  return (
    <html lang={awaitedParams.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      >    <main className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-center mb-8 space-x-2">
            <CalendarDays className="h-8 w-8 text-[#00B900]" />
            <h1 className="text-2xl font-bold">{t('title')}</h1>
          </div>
          <LiffProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </LiffProvider>
        </main>
      </body>
    </html>
  );
}
